name: Build

on:
  push:
    branches: [ "main", "release/*", "story/*", "task/*", "sub-task/*" ]
    paths:
      - 'docs-*/**'
      - 'pom.xml'
      - '.github/workflows/**'
  pull_request:
    #    branches: [ "main" ]
    types: [opened, synchronize, reopened]
    paths:
      - 'docs-*/**'
      - 'pom.xml'
  workflow_dispatch:

env:
  API_DOCKER_REGISTRY: ghcr.io

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')  || github.event_name == 'pull_request' # runs only if it's a branch or a pull request

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven build
        run: mvn -B package --file pom.xml -DskipTests=true

  test_job:
    name: Run tests
    needs: build_job
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')  || github.event_name == 'pull_request' # runs only if it's a branch or a pull request
    environment: ci

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Prepare test environment
        env:
          GETTHEDOCS_REPO_AWS_S3_BUCKETNAME: ${{ secrets.TEST_AWS_BUCKETNAME }}
          GETTHEDOCS_REPO_AWS_S3_REGION: ${{ secrets.TEST_AWS_REGION }}
        run: |
          sed -i "s/_BUCKETNAME_/$GETTHEDOCS_REPO_AWS_S3_BUCKETNAME/g" src/test/resources/document-engine.properties
          sed -i "s/_BUCKET_REGION_/$GETTHEDOCS_REPO_AWS_S3_REGION/g" src/test/resources/document-engine.properties

      - name: Maven verify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn -B verify --file pom.xml -Dspring.profiles.active=local

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/target/surefire-reports/TEST-*.xml
            **/target/failsafe-reports/TEST-*.xml

  test_report_job:
    name: Create test reports
    needs:
      - build_job
      - test_job

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')  || github.event_name == 'pull_request' # runs only if it's a branch or a pull request

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Prepare test environment
        env:
          GETTHEDOCS_REPO_AWS_S3_BUCKETNAME: ${{ secrets.TEST_AWS_BUCKETNAME }}
          GETTHEDOCS_REPO_AWS_S3_REGION: ${{ secrets.TEST_AWS_REGION }}
        run: |
          sed -i "s/_BUCKETNAME_/$GETTHEDOCS_REPO_AWS_S3_BUCKETNAME/g" src/test/resources/document-engine.properties
          sed -i "s/_BUCKET_REGION_/$GETTHEDOCS_REPO_AWS_S3_REGION/g" src/test/resources/document-engine.properties

      - name: Maven site
        run: mvn -B verify site --file pom.xml -Dspring.profiles.active=local


      - uses: dorny/test-reporter@v2
        with:
          artifact: test-results            # artifact name
          name: Tests                       # Name of the check run which will be created
          path: '**/*.xml'                  # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results

      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: '**/target/site/**'

  coverage_job:
    name: Coverage check
    needs:
      - build_job
      - test_job
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')  || github.event_name == 'pull_request' # runs only if it's a branch or a pull request
    environment: ci

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Prepare test environment
        env:
          GETTHEDOCS_REPO_AWS_S3_BUCKETNAME: ${{ secrets.TEST_AWS_BUCKETNAME }}
          GETTHEDOCS_REPO_AWS_S3_REGION: ${{ secrets.TEST_AWS_REGION }}
        run: |
          sed -i "s/_BUCKETNAME_/$GETTHEDOCS_REPO_AWS_S3_BUCKETNAME/g" src/test/resources/document-engine.properties
          sed -i "s/_BUCKET_REGION_/$GETTHEDOCS_REPO_AWS_S3_REGION/g" src/test/resources/document-engine.properties

      - name: Maven verify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn -B verify --file pom.xml -Dspring.profiles.active=local -Pcoverage

      - name: Run Clover coverage and upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: document-engine
